summary: ''
description: ''
lock: '!inline f/prj_content_forge/flows/process_recording/select_config.script.lock'
kind: script
schema:
  $schema: 'https://json-schema.org/draft/2020-12/schema'
  type: object
  properties:
    index:
      type: object
      description: ''
      default: null
    posts:
      type: object
      description: ''
      default: null
  required:
    - index
    - posts
